services:
  api:
    # 백엔드 API 서비스 설정
    build:
      context: . # 현재 디렉토리를 빌드 컨텍스트로 사용
      dockerfile: Dockerfile.dev # 개발용 Dockerfile 사용
    container_name: soapft-be
    ports:
      - '7777:7777' # 호스트와 컨테이너 포트 매핑
    volumes:
      - .:/app # 현재 디렉토리를 컨테이너의 /app에 마운트
      - /app/node_modules # node_modules 볼륨 분리
    environment:
      - NODE_ENV=development # 개발 환경으로 설정
      - DB_HOST=postgres # PostgreSQL 서비스 이름
      - DB_PORT=5432 # PostgreSQL 포트
      - DB_USERNAME=postgres # PostgreSQL 사용자 이름
      - DB_PASSWORD=postgres # PostgreSQL 비밀번호
      - DB_DATABASE=soapft # PostgreSQL 데이터베이스 이름
    depends_on:
      - postgres # PostgreSQL 서비스가 먼저 시작되어야 함
    networks:
      - app-network # 앱 네트워크에 연결

  postgres:
    # PostgreSQL 데이터베이스 서비스 설정
    image: postgres:14-alpine
    container_name: soapft-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soapft
    volumes:
      - postgres-data:/var/lib/postgresql/data # 데이터 볼륨 마운트
    networks:
      - app-network # 앱 네트워크에 연결

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: # PostgreSQL 데이터 볼륨 정의
