name: 이슈 템플릿
description: 이슈 템플릿입니다
title: '[FE/BE] 이슈 제목'
labels: ['기능추가']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📌 이슈 내용
        이슈에 대해 설명해주세요.

  - type: textarea
    id: issue-description
    attributes:
      label: 이슈 설명
      placeholder: 이슈에 대한 상세 내용을 적어주세요
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## ✅ 작업 상세

  - type: checkboxes
    id: tasks
    attributes:
      label: 작업 목록
      description: 이슈를 해결하기 위한 작업 목록을 체크해주세요
      options:
        - label: todo1
        - label: todo2

  - type: dropdown
    id: label-selection
    attributes:
      label: 라벨 선택
      description: 이슈의 종류를 선택해주세요 (이 항목은 삭제하고 사이드바에서 직접 라벨을 선택해도 됩니다)
      options:
        - 기능추가(새로운 기능 추가)
        - 리팩토링(기능추가, 버그픽스와 관련없는 코드 개선 작업)
        - 문서(문서 작성)
        - 버그픽스(버그 수정)
        - 스타일(UI 수정)
        - 테스트(테스트 코드 작성)
