name: 이슈 템플릿
description: 이슈 템플릿입니다
title: '[FE/BE]'
labels: ['기능추가']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📌 이슈 내용

  - type: textarea
    id: issue-description
    attributes:
      label: 이슈 설명
      placeholder: 이슈에 대한 상세 내용을 적어주세요
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## ✅ 작업 상세

  - type: textarea
    id: todo-list
    attributes:
      label: 할 일 목록
      placeholder: |
        - [ ] 할 일 1
        - [ ] 할 일 2
      render: markdown
    validations:
      required: false
